// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.173
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TrailingWhitespace
{
    static class Vsix
    {
        public const string Id = "4c1a78e6-e7b8-4aa9-8812-4836e051ff6d";
        public const string Name = "Trailing Whitespace Visualizer";
        public const string Description = "Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace";
        public const string Language = "en-US";
        public const string Version = "2.4";
        public const string Author = "Mads Kristensen";
        public const string Tags = "whitespace";
    }
}
