// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TrailingWhitespace
{
    internal sealed partial class Vsix
    {
        public const string Id = "dac582ef-fc73-42f6-ad45-afaad93d88a4";
        public const string Name = "Trailing Whitespace Visualizer";
        public const string Description = @"Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace";
        public const string Language = "en-US";
        public const string Version = "2.6";
        public const string Author = "Mads Kristensen";
        public const string Tags = "whitespace";
    }
}
